version: "3"

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres:9.6
    container_name: ck-theme_postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: bitnami/keycloak:18.0.0-debian-11-r0
    container_name: ck-theme_keycloak
    environment:
      KEYCLOAK_DATABASE_HOST: postgres
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_USER: keycloak
      KEYCLOAK_DATABASE_SCHEMA: public
      KEYCLOAK_DATABASE_PASSWORD: password
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KEYCLOAK_PRODUCTION: "false"
      KEYCLOAK_ENABLE_TLS: "false"
    ports:
      - 8080:8080
    volumes:
      - ./themes/custom:/opt/bitnami/keycloak/themes/custom
    depends_on:
      - postgres

  maildev:
    container_name: maildev
    image: djfarrelly/maildev:1.0.0-rc2
    ports:
      - 9999:80
      - 25